# Code Deploy 배포 설정

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwirte: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    -location: stop.sh # Nginx 와 연결되어 있지 않은 스프링 부트 종료
      timeout: 60
      reunas: ec2-user

  ApplicationStart:
    - location: start.sh # Nginx 와 연결되어 있지 않은 Port 로 새 버전의 스프링 부트 시작
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상 실행됬는지 확인
      timeout: 60
      runas: ec2-user