# Code Deploy 배포 설정

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwirte: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user

  ApplicationService:
    - location: health.sh # 새 스프링 부트가 정상 실행됬는지 확인
      timeout: 60
      runas: ec2-user